services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: broker_mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./homeassistant:/config
    ports:
      - "8123:8123"
    restart: unless-stopped

  nodered:
    image: nodered/node-red:latest
    container_name: simulador_sensores
    environment:
      - TZ=Europe/Madrid
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data
    restart: unless-stopped